version: '3'
services:
  vault:
    image: vault
    ports:
      - "8200:8200"
    volumes:
      - ./vault/file:/vault/file:rw
      - ./vault/config:/vault/config:rw
      - ./vault/logs:/vault/logs:rw
    cap_add:
      - IPC_LOCK
    command: server
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: changeme
  web:
    build: ./app/
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/code
    depends_on:
      - vault
